### PR TITLE
Change del.p_=0 to del.p_=nullptr

### PR DESCRIPTION
**Pull request by paulharris**
A simple change (I hope) that cleans up compiler warnings and errors.

### CODE REVIEW

**Comment by pdimov** [comment]
Let's await the resolution of https://github.com/boostorg/config/pull/431.

**Comment by paulharris** [comment]
Ok, thanks!   Close this issue when appropriate, thanks :)

**Comment by pdimov** [comment]
BOOST_NULLPTR has been merged, so you can update the PR to use it if you like.

**Comment by paulharris** [comment]
How is this?

**Comment by pdimov** [comment]
Perfection.

**Pull request merged**
